{{- if and .Values.agent.clientId .Values.agent.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agent.credentialsSecretRef.name }}
  labels:
    {{- include "obsyk-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  client_id: {{ .Values.agent.clientId | quote }}
  private_key: {{ .Values.agent.privateKey | quote }}
{{- end }}
